### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by jjeremycai** [ItalicHQ/landing-html#1]
## Links
**CTA links**
For Suppliers - mailto:suppliers@shopitalic.com
Careers - mailto:careers@shopitalic.com

**Text links**
Call our CEO - https://calendly.com/italic
Text: 855-123-4567 - `<a href="iMessage://4085551212">Text: 855-123-4567 </a>`

**Social links**
Twitter - https://twitter.com/shopitalic
Instagram - http://instagram.com/italichq/ - Please note, Instagram is currently missing from the footer
Youtube - https://youtube.com/glossierTV
Facebook - http://facebook.com/shopitalic

**Comment by romanlnk** [comment]
@jjeremycai http://jsource.pro/projects/storeitalic/landing/ - fixed links

**Comment by jjeremycai** [comment]
@romanlnk Can you actually switch the following links?

For Suppliers link to https://airtable.com/shr58IS2RHcngXHef
Careers link to https://airtable.com/shrf1VvhxX9OhPE7u
